theme: minima
title: My first Github Pages blog
author: Felipe Sciammarella 
email: fl.sciammarella@ufrj.br
description: > # this means to ignore newlines until "baseurl:"
  I never liked nice descriptions.

# social links
twitter_username: lipescia
github_username:  FSciammarella

show_excerpts: true # set to false to remove excerpts on the homepage
